image: ubuntu

before_script:
  - apt-get update -qq
  - apt-get install sudo
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEV_SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

develop_staging:
  type: deploy
  environment:
    name: develop
  script:
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "pm2 ls"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "pm2 delete jeanswest-club > /dev/null 2>&1 || FAILED=true"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "rm -rf * /home/gitlab/jeanswest-club/"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "mkdir -p /home/gitlab/jeanswest-club/"

    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-club/ && git clone git@gitlab.avakatan.ir:jeanswest-project/backend-jeanswest.git"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-club/backend-jeanswest/ && yarn"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-club/backend-jeanswest/ && yarn prebuild"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-club/backend-jeanswest/ && yarn build"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cp /home/gitlab/.env.production /home/gitlab/jeanswest-club/backend-jeanswest/env/"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir  "cd /home/gitlab/jeanswest-club/backend-jeanswest/ && pm2 start yarn --interpreter bash --name jeanswest-club -- start:prod"
    - echo "http://JWApp-Dev-0-1.AVAKATAN.ir:5000/"

  only:
    - develop