export const CUSTOMER_AUTH_SERVICE = 'CUSTOMER_AUTH_SERVICE';
export const USER_CUSTOMER_SERVICE = 'USER_CUSTOMER_SERVICE';
export const CUSTOMER_LOCAL_STRATEGY = 'CUSTOMER_LOCAL_STRATEGY';
export const CUSTOMER_JWT_STRATEGY = 'CUSTOMER_JWT_STRATEGY';
