export const BASE_REPO = 'BASE_REPOSITORY';
export const ERP_BRANCH_REPO = 'ERP_BRANCH_REPOSITORY';
export const ERP_PRODUCT_REPO = 'ERP_PRODUCT_REPOSITORY';
export const ERP_USER_REPO = 'ERP_USER_REPOSITORY';
